
### Variables
@url = http://localhost:3000/api/v1
@type = Grass

@id = 6914fcfe08e0b0edf16d6867

@name = IvySaur

### All Pokemon
GET {{url}}/pokemon/

### PPokemon by Name
GET {{url}}/pokemon/byName/{{name}}

## Pokemon by ID
GET {{url}}/pokemon/byId/{{id}}

### Random Pokemon
GET {{url}}/pokemon/random

### Specific Pokemon
GET {{url}}/pokemon/2

### Random with type
GET {{url}}/pokemon/random/{{type}}




### Add a new pokemon
POST {{url}}/pokemon/add
content-type: application/json

{
    "number": 12,
    "name": "Butterfree",
    "type": "Bug"
}